name: Go Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe #v2
      with:
        go-version: 1.20

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v ./...
